# dag config
dag_id: 'info'
schedule: '*/10 * * * *'
max_active_runs: 1
catchup: False

# task config
tasks:
  release:
    url: "https://api.github.com/repos/{OWNER}/{REPO}/tags"
    params:
      per_page: 30
      page: 1
    columns:
      ID: "node_id"
      REL_NM: "name"
  project:
    url: "https://api.github.com/repos/{OWNER}/{REPO}/projects"
    params:
      state: "all"
      per_page: 30
      page: 1
    columns:
      ID: "node_id"
      PROJ_NM: "name"
      BODY: "body"
      PROJ_NO: "number"
      PROJ_ST: "state"
      CREATED_AT: "created_at"
      UPDATED_AT: "updated_at"
  language:
    url: "https://api.github.com/repos/{OWNER}/{REPO}/languages"
  fork:
    url: "https://api.github.com/repos/{OWNER}/{REPO}/forks"
    params:
      # q:
      # sort: comments, reactions, reactions-+1, reactions--1, reactions-smile, reactions-thinking_face, reactions-heart, reactions-tada, interactions, created, updated
      per_page: 30
      page: 1
    columns:
      ID: "node_id"
      FORK_NM: "name"
      OWNER_ID: "owner.node_id"
      OWNER_NM: "owner.login"
      URL: "url"
      CREATED_AT: "created_at"
      UPDATED_AT: "updated_at"